# Generated by Django 3.1.7 on 2021-02-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('answer', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('difficulty', models.IntegerField()),
                ('responses', models.ManyToManyField(to='flashcard.Response')),
            ],
        ),
    ]
