# Generated by Django 3.1.7 on 2021-02-25 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=120, verbose_name='Choice')),
                ('position', models.IntegerField(verbose_name='position')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='description',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='title',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='choice',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='flashcard.flashcard'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('flashcard', 'position'), ('flashcard', 'choice')},
        ),
    ]
