# Generated by Django 3.1.7 on 2021-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_auto_20210225_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='correct',
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('flashcard', 'choice_text'), ('flashcard', 'position')},
        ),
    ]
